# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               lcarbonaro
tagline:             'just a blog... nothing to see here... move along'
description:         'Just another Jekyll blog on github.io'
url:                 http://lcarbonaro.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Les Carbonaro
  url:               https://twitter.com/lcarbonaro
  email:             lcarbonaro@gmail.com

# Custom vars
version:             1.0.0
